FROM docker.uclv.cu/python:3.10-alpine3.15

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/app
WORKDIR /home/app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt